version: "3"
services:
  development:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        source: notused # name of the volume, see below
        target: /usr/src/app/node_modules
        volume:
          nocopy: true
    # volumes:
    # This is so that changes on the host are picked up in the
    # container, which helps with developing locally without having
    # to rebuild the image.
    # - .:/usr/src/app
    # This is to make sure that we don't mount the host node_modules
    # into the container, since we want to use the packages that are
    # installed for the image, not the host os.
    # - notused:/usr/src/app/node_modules
    # - notused:/usr/src/app/.next
    # command: ls node_modules

  production:
    build:
      context: .
      target: release
    ports:
      - 3000:3000

volumes:
  notused:
